const products = [
	// Software - Bluestacks
	{
		id: 1,
		name: "BlueStacks 4",
		category: "software",
		price: 29.99,
		badge: "PAID",
		description: "The fastest and safest Android emulator for PC",
		image: "assets/images/bluestacks4.svg",
		features: [
			"High performance Android emulation",
			"Full game controller support",
			"Multi-instance manager",
			"Optimized for gaming",
		],
	},
	{
		id: 2,
		name: "BlueStacks 5",
		category: "software",
		price: 39.99,
		badge: "LATEST",
		description: "Latest version with enhanced performance and features",
		image: "assets/images/bluestacks5.svg",
		features: [
			"Ultra-fast performance",
			"Modern UI & UX",
			"Better battery efficiency",
			"Advanced game optimization",
		],
	},
	// Software - MSI
	{
		id: 3,
		name: "MSI 4",
		category: "software",
		price: 24.99,
		badge: "PAID",
		description: "Professional mobile streaming utility",
		image: "assets/images/msi4.svg",
		features: [
			"Mobile to PC streaming",
			"Game optimization",
			"Screen recording",
			"Performance monitoring",
		],
	},
	{
		id: 4,
		name: "MSI 5",
		category: "software",
		price: 34.99,
		badge: "LATEST",
		description: "Next-generation mobile streaming with advanced features",
		image: "assets/images/msi5.svg",
		features: [
			"Ultra-fast streaming",
			"AI optimization",
			"Advanced cooling control",
			"RGB lighting sync",
		],
	},
	// Software - Emulator
	{
		id: 5,
		name: "Android Emulator Pro",
		category: "software",
		price: 19.99,
		badge: "POPULAR",
		description: "Lightweight and powerful Android emulator",
		image: "assets/images/emulator.svg",
		features: [
			"Lightweight installation",
			"Quick startup time",
			"Full Android compatibility",
			"Low resource usage",
		],
	},

	// Operating Systems
	{
		id: 6,
		name: "Windows 10 Pro Lite",
		category: "os",
		price: 49.99,
		badge: "LITE",
		description: "Optimized Windows 10 Pro with reduced bloatware",
		image: "assets/images/windows10lite.svg",
		features: [
			"Reduced bloatware",
			"Faster performance",
			"All Pro features included",
			"Lifetime activation",
		],
	},
	{
		id: 7,
		name: "Windows 10 Pro (Full)",
		category: "os",
		price: 59.99,
		badge: "FULL",
		description: "Complete Windows 10 Pro with all features",
		image: "assets/images/windows10full.svg",
		features: [
			"Full Windows features",
			"Enterprise ready",
			"Advanced security",
			"Lifetime support",
		],
	},
	{
		id: 8,
		name: "Windows 11 Pro Lite",
		category: "os",
		price: 69.99,
		badge: "LITE",
		description: "Optimized Windows 11 Pro - faster and cleaner",
		image: "assets/images/windows11lite.svg",
		features: [
			"Optimized for speed",
			"Modern UI",
			"Minimal bloatware",
			"Lifetime activation",
		],
	},
	{
		id: 9,
		name: "Windows 11 Pro (Full)",
		category: "os",
		price: 79.99,
		badge: "LATEST",
		description: "Complete Windows 11 Pro with all latest features",
		image: "assets/images/windows11full.svg",
		features: [
			"Latest Windows 11",
			"AI integration",
			"Advanced widgets",
			"Lifetime support",
		],
	},
	{
		id: 10,
		name: "Ubuntu Linux Pro",
		category: "os",
		price: 39.99,
		badge: "FREE+",
		description: "Ubuntu with all drivers pre-installed",
		image: "assets/images/ubuntu.svg",
		features: [
			"Latest Ubuntu LTS",
			"All drivers included",
			"Development tools ready",
			"Community support",
		],
	},
	{
		id: 11,
		name: "Debian Linux Complete",
		category: "os",
		price: 34.99,
		badge: "DISTRO",
		description: "Debian with optimized drivers and packages",
		image: "assets/images/debian.svg",
		features: [
			"Stable Debian release",
			"Pre-configured drivers",
			"Optimized packages",
			"Long-term support",
		],
	},
	{
		id: 12,
		name: "Fedora Linux Advanced",
		category: "os",
		price: 29.99,
		badge: "DISTRO",
		description: "Latest Fedora with cutting-edge software",
		image: "assets/images/fedora.svg",
		features: [
			"Latest Fedora release",
			"Modern development tools",
			"Optimized performance",
			"Active community",
		],
	},

	// Design & Development
	{
		id: 13,
		name: "Professional Logo Design",
		category: "design",
		price: 79.99,
		badge: "DESIGN",
		description: "Custom professional logo design service",
		image: "assets/images/logo_design.svg",
		features: [
			"Custom design",
			"3-4 revision rounds",
			"Multiple concepts",
			"High-resolution files",
		],
	},
	{
		id: 14,
		name: "Website Design Package",
		category: "design",
		price: 299.99,
		badge: "DESIGN",
		description: "Complete website design with modern UI/UX",
		image: "assets/images/website_design.svg",
		features: [
			"Responsive design",
			"SEO optimized",
			"Modern aesthetics",
			"Mobile-friendly",
		],
	},
	{
		id: 15,
		name: "Website Development",
		category: "design",
		price: 499.99,
		badge: "DEVELOP",
		description: "Full website development with backend",
		image: "assets/images/website_dev.svg",
		features: [
			"Frontend + Backend",
			"Database setup",
			"Deployment included",
			"3 months support",
		],
	},
	{
		id: 16,
		name: "Video Editing Service",
		category: "design",
		price: 99.99,
		badge: "MEDIA",
		description: "Professional video editing and post-production",
		image: "assets/images/video_edit.svg",
		features: [
			"Color grading",
			"Effects & transitions",
			"4K support",
			"Multiple revisions",
		],
	},
	{
		id: 17,
		name: "Photo Editing & Enhancement",
		category: "design",
		price: 49.99,
		badge: "MEDIA",
		description: "Professional photo editing and retouching",
		image: "assets/images/photo_edit.svg",
		features: [
			"Retouching included",
			"Background removal",
			"Color correction",
			"Up to 50 photos",
		],
	},

	// Gaming & Utilities
	{
		id: 18,
		name: "Free Fire Paid Sensitivity",
		category: "gaming",
		price: 9.99,
		badge: "GAMING",
		description: "Optimized sensitivity settings for Free Fire",
		image: "assets/images/free_fire_sens.svg",
		features: [
			"Pro player settings",
			"HD graphics optimized",
			"Lag reduction",
			"Instant delivery",
		],
	},
	{
		id: 19,
		name: "PC Optimization Service",
		category: "gaming",
		price: 29.99,
		badge: "UTILITY",
		description: "Complete PC optimization and cleanup",
		image: "assets/images/pc_optimization.svg",
		features: [
			"Performance boost",
			"Registry cleanup",
			"Startup optimization",
			"Malware removal",
		],
	},
	{
		id: 20,
		name: "Discord Bot Development",
		category: "gaming",
		price: 149.99,
		badge: "DEVELOP",
		description: "Custom Discord bot with advanced features",
		image: "assets/images/discord_bot.svg",
		features: [
			"Custom commands",
			"Moderation tools",
			"Database integration",
			" 3 months support",
		],
	},
	{
		id: 21,
		name: "TCP Bot Package",
		category: "gaming",
		price: 59.99,
		badge: "DEVELOP",
		description: "Advanced TCP bot with multiple features",
		image: "assets/images/tcp_bot.svg",
		features: [
			"Multi-function bot",
			"Auto-management",
			"Custom integration",
			"Updates included",
		],
	},
	{
		id: 22,
		name: "Free Fire Gaming Panel",
		category: "gaming",
		price: 129.99,
		badge: "PANEL",
		description: "Complete gaming panel management system",
		image: "assets/images/free_fire_panel.svg",
		features: [
			"User dashboard",
			"Account management",
			"Analytics tracking",
			"Admin panel included",
		],
	},
];

// Product categories mapping
const categories = {
	software: "Software & Emulators",
	os: "Operating Systems",
	gaming: "Gaming & Utilities",
	design: "Design & Development",
};
