const products = [
	// Software - Bluestacks
	{
		id: 1,
		name: "BlueStacks 4",
		category: "software",
		price: 29.99,
		badge: "PAID",
		description: "The fastest and safest Android emulator for PC",
		image: "assets/images/BS4.jpg",
		features: [
			"High performance Android emulation",
			"Full game controller support",
			"Multi-instance manager",
			"Optimized for gaming",
		],
	},
	{
		id: 2,
		name: "BlueStacks 5",
		category: "software",
		price: 39.99,
		badge: "LATEST",
		description: "Latest version with enhanced performance and features",
		image: "assets/images/BS5.jpeg",
		features: [
			"Ultra-fast performance",
			"Modern UI & UX",
			"Better battery efficiency",
			"Advanced game optimization",
		],
	},
	// Software - MSI
	{
		id: 3,
		name: "MSI 4",
		category: "software",
		price: 24.99,
		badge: "PAID",
		description: "Professional mobile streaming utility",
		image: "assets/images/msi4.jpg",
		features: [
			"Mobile to PC streaming",
			"Game optimization",
			"Screen recording",
			"Performance monitoring",
		],
	},
	{
		id: 4,
		name: "MSI 5",
		category: "software",
		price: 34.99,
		badge: "LATEST",
		description: "Next-generation mobile streaming with advanced features",
		image: "assets/images/msi5.jpg",
		features: [
			"Ultra-fast streaming",
			"AI optimization",
			"Advanced cooling control",
			"RGB lighting sync",
		],
	},
	// Software - Emulator
	{
		id: 5,
		name: "Android Emulator Pro",
		category: "software",
		price: 19.99,
		badge: "POPULAR",
		description: "Lightweight and powerful Android emulator",
		image: "assets/images/Android Emulator Pro.jpg",
		features: [
			"Lightweight installation",
			"Quick startup time",
			"Full Android compatibility",
			"Low resource usage",
		],
	},

	// Operating Systems
	{
		id: 6,
		name: "Windows 10 Pro Lite",
		category: "os",
		price: 49.99,
		badge: "LITE",
		description: "Optimized Windows 10 Pro with reduced bloatware",
		image: "assets/images/Windows 10 Pro Lite.jpeg",
		features: [
			"Reduced bloatware",
			"Faster performance",
			"All Pro features included",
			"Lifetime activation",
		],
	},
	{
		id: 7,
		name: "Windows 10 Pro (Full)",
		category: "os",
		price: 59.99,
		badge: "FULL",
		description: "Complete Windows 10 Pro with all features",
		image: "assets/images/Windows 10 Pro (Full).jpg",
		features: [
			"Full Windows features",
			"Enterprise ready",
			"Advanced security",
			"Lifetime support",
		],
	},
	{
		id: 8,
		name: "Windows 11 Pro Lite",
		category: "os",
		price: 69.99,
		badge: "LITE",
		description: "Optimized Windows 11 Pro - faster and cleaner",
		image: "assets/images/Windows 11 Pro Lite.jpg",
		features: [
			"Optimized for speed",
			"Modern UI",
			"Minimal bloatware",
			"Lifetime activation",
		],
	},
	{
		id: 9,
		name: "Windows 11 Pro (Full)",
		category: "os",
		price: 79.99,
		badge: "LATEST",
		description: "Complete Windows 11 Pro with all latest features",
		image: "assets/images/Windows 11 Pro (Full).jpeg",
		features: [
			"Latest Windows 11",
			"AI integration",
			"Advanced widgets",
			"Lifetime support",
		],
	},
	{
		id: 10,
		name: "Ubuntu Linux Pro",
		category: "os",
		price: 39.99,
		badge: "FREE+",
		description: "Ubuntu with all drivers pre-installed",
		image: "assets/images/Ubuntu Linux Pro.jpg",
		features: [
			"Latest Ubuntu LTS",
			"All drivers included",
			"Development tools ready",
			"Community support",
		],
	},
	{
		id: 11,
		name: "Debian Linux Complete",
		category: "os",
		price: 34.99,
		badge: "DISTRO",
		description: "Debian with optimized drivers and packages",
		image: "assets/images/Debian Linux Complete.jpeg",
		features: [
			"Stable Debian release",
			"Pre-configured drivers",
			"Optimized packages",
			"Long-term support",
		],
	},
	{
		id: 12,
		name: "Fedora Linux Advanced",
		category: "os",
		price: 29.99,
		badge: "DISTRO",
		description: "Latest Fedora with cutting-edge software",
		image: "assets/images/Fedora Linux Advanced.png",
		features: [
			"Latest Fedora release",
			"Modern development tools",
			"Optimized performance",
			"Active community",
		],
	},

	// Design & Development
	{
		id: 13,
		name: "Professional Logo Design",
		category: "design",
		price: 79.99,
		badge: "DESIGN",
		description: "Custom professional logo design service",
		image: "assets/images/Professional Logo Design.gif",
		features: [
			"Custom design",
			"3-4 revision rounds",
			"Multiple concepts",
			"High-resolution files",
		],
	},
	{
		id: 14,
		name: "Website Design Package",
		category: "design",
		price: 299.99,
		badge: "DESIGN",
		description: "Complete website design with modern UI/UX",
		image: "assets/images/Website Design Package.jpeg",
		features: [
			"Responsive design",
			"SEO optimized",
			"Modern aesthetics",
			"Mobile-friendly",
		],
	},
	{
		id: 15,
		name: "Website Development",
		category: "design",
		price: 499.99,
		badge: "DEVELOP",
		description: "Full website development with backend",
		image: "assets/images/Website Development.png",
		features: [
			"Frontend + Backend",
			"Database setup",
			"Deployment included",
			"3 months support",
		],
	},
	{
		id: 16,
		name: "Video Editing Service",
		category: "design",
		price: 99.99,
		badge: "MEDIA",
		description: "Professional video editing and post-production",
		image: "assets/images/Video Editing Service.jpg",
		features: [
			"Color grading",
			"Effects & transitions",
			"4K support",
			"Multiple revisions",
		],
	},
	{
		id: 17,
		name: "Photo Editing & Enhancement",
		category: "design",
		price: 49.99,
		badge: "MEDIA",
		description: "Professional photo editing and retouching",
		image: "assets/images/Photo Editing & Enhancement.jpeg",
		features: [
			"Retouching included",
			"Background removal",
			"Color correction",
			"Up to 50 photos",
		],
	},

	// Gaming & Utilities
	{
		id: 18,
		name: "Free Fire Paid Sensitivity",
		category: "gaming",
		price: 9.99,
		badge: "GAMING",
		description: "Optimized sensitivity settings for Free Fire",
		image: "assets/images/Free Fire Paid Sensitivity.jpg",
		features: [
			"Pro player settings",
			"HD graphics optimized",
			"Lag reduction",
			"Instant delivery",
		],
	},
	{
		id: 19,
		name: "PC Optimization Service",
		category: "gaming",
		price: 29.99,
		badge: "UTILITY",
		description: "Complete PC optimization and cleanup",
		image: "assets/images/PC Optimization Service.jpeg",
		features: [
			"Performance boost",
			"Registry cleanup",
			"Startup optimization",
			"Malware removal",
		],
	},
	{
		id: 20,
		name: "Discord Bot Development",
		category: "gaming",
		price: 149.99,
		badge: "DEVELOP",
		description: "Custom Discord bot with advanced features",
		image: "assets/images/Discord Bot Development.jpg",
		features: [
			"Custom commands",
			"Moderation tools",
			"Database integration",
			" 3 months support",
		],
	},
	{
		id: 21,
		name: "TCP Bot Package",
		category: "gaming",
		price: 59.99,
		badge: "DEVELOP",
		description: "Advanced TCP bot with multiple features",
		image: "assets/images/TCP Bot Package.jpg",
		features: [
			"Multi-function bot",
			"Auto-management",
			"Custom integration",
			"Updates included",
		],
	},
	{
		id: 22,
		name: "Free Fire Gaming Panel",
		category: "gaming",
		price: 129.99,
		badge: "PANEL",
		description: "Complete gaming panel management system",
		image: "assets/images/Free Fire Gaming Panel.jpg",
		features: [
			"User dashboard",
			"Account management",
			"Analytics tracking",
			"Admin panel included",
		],
	},
	// Windows Terminal Customization
	{
		id: 23,
		name: "Windows Terminal Customization",
		category: "customization",
		price: 19.99,
		badge: "TERMINAL",
		description: "Professional Windows Terminal themes and configurations",
		image: "assets/images/Windows Terminal Customization.png",
		features: [
			"20+ custom themes",
			"PowerShell profiles",
			"Oh-My-Posh integration",
			"Auto-installation scripts",
		],
	},
	// Linux Terminal Customization
	{
		id: 24,
		name: "Linux Terminal Customization",
		category: "customization",
		price: 14.99,
		badge: "TERMINAL",
		description: "Beautiful Bash, Zsh, and Fish shell configurations",
		image: "assets/images/Linux Terminal Customization.jpg",
		features: [
			"15+ shell themes",
			".bashrc/.zshrc configs",
			"Plugin setups",
			"Font recommendations",
		],
	},
	// Mac Terminal Pro
	{
		id: 25,
		name: "macOS Terminal Pro",
		category: "customization",
		price: 24.99,
		badge: "TERMINAL",
		description: "Premium macOS terminal themes and utilities",
		image: "assets/images/macOS Terminal Pro.jpeg",
		features: [
			"iTerm2 themes",
			"Homebrew optimization",
			"Zsh customization",
			"Developer tools setup",
		],
	},
	// Terminal Icons & Fonts
	{
		id: 26,
		name: "Terminal Icons & Fonts Pack",
		category: "customization",
		price: 9.99,
		badge: "FONTS",
		description: "50+ terminal fonts and icon packs",
		image: "assets/images/Terminal Icons & Fonts Pack.jpg",
		features: [
			"Nerd fonts collection",
			"Icon packs included",
			"Installation scripts",
			"Font preview guide",
		],
	},
	// NeoVim Setup
	{
		id: 27,
		name: "NeoVim Complete Setup",
		category: "customization",
		price: 29.99,
		badge: "EDITOR",
		description: "Complete NeoVim configuration with plugins",
		image: "assets/images/NeoVim Complete Setup.jpg",
		features: [
			"Pre-configured plugins",
			"LSP setup included",
			"Custom keybindings",
			"Lua configuration",
		],
	},
	// VS Code Terminal Theme
	{
		id: 28,
		name: "VS Code Terminal Pro",
		category: "customization",
		price: 12.99,
		badge: "EDITOR",
		description: "Advanced VS Code integrated terminal themes",
		image: "assets/images/VS Code Terminal Pro.png",
		features: [
			"10+ terminal themes",
			"Font optimization",
			"Keybinding presets",
			"Extension recommendations",
		],
	},
	// Prompt Customization Pack
	{
		id: 29,
		name: "Shell Prompt Customization",
		category: "customization",
		price: 11.99,
		badge: "PROMPT",
		description: "Custom shell prompts for any OS",
		image: "assets/images/Shell Prompt Customization.png",
		features: [
			"30+ prompt designs",
			"Git integration",
			"Custom functions",
			"Quick installer",
		],
	},
	// Docker Terminal Setup
	{
		id: 30,
		name: "Docker Terminal Setup",
		category: "customization",
		price: 17.99,
		badge: "DOCKER",
		description: "Optimized terminal environment for Docker",
		image: "assets/images/Docker Terminal Setup.png",
		features: [
			"Docker aliases",
			"Container monitoring",
			"Compose templates",
			"Auto-completion setup",
		],
	},
	// Professional Gmail Setup
	{
		id: 31,
		name: "Professional Gmail Setup",
		category: "design",
		price: 24.99,
		badge: "EMAIL",
		description: "Professional Gmail configuration and optimization",
		image: "assets/images/Professional Gmail.svg",
		features: [
			"Custom domain setup",
			"Gmail filters & rules",
			"Signature templates",
			"Security optimization",
		],
	},
	// Social Media Profile Optimization
	{
		id: 32,
		name: "Social Media Profile Optimization",
		category: "design",
		price: 34.99,
		badge: "SOCIAL",
		description:
			"Complete social media profile optimization across all platforms",
		image: "assets/images/Social Media Profile.svg",
		features: [
			"Bio optimization",
			"Profile aesthetics",
			"Content calendar setup",
			"Growth strategy guide",
		],
	},
];

// Product categories mapping
const categories = {
	software: "Software & Emulators",
	os: "Operating Systems",
	gaming: "Gaming & Utilities",
	design: "Design & Development",
	customization: "Terminal & Customization",
};
